package task

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func newDocsTestRoot() *cobra.Command {
	root := &cobra.Command{Use: "nostromo", Short: "root"}
	add := &cobra.Command{Use: "add", Short: "add things"}
	add.AddCommand(&cobra.Command{Use: "cmd [key.path]", Short: "add a command", Run: func(*cobra.Command, []string) {}})
	add.AddCommand(&cobra.Command{Use: "sub [key.path]", Short: "add a sub", Run: func(*cobra.Command, []string) {}})
	root.AddCommand(add)
	root.AddCommand(&cobra.Command{Use: "show", Short: "show things", Run: func(*cobra.Command, []string) {}})
	root.AddCommand(&cobra.Command{Use: "run", Short: "hidden", Hidden: true, Run: func(*cobra.Command, []string) {}})
	return root
}

func TestGenerateDocs(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "reference")
	root := newDocsTestRoot()

	if code := GenerateDocs(root, dir); code != 0 {
		t.Fatalf("expected exit code 0, got %d", code)
	}

	for _, name := range []string{"nostromo.md", "nostromo_add.md", "nostromo_add_cmd.md", "nostromo_add_sub.md", "nostromo_show.md", "SUMMARY.md"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("expected %s to be generated: %s", name, err)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "nostromo_run.md")); !os.IsNotExist(err) {
		t.Errorf("hidden command should not be documented")
	}

	b, err := os.ReadFile(filepath.Join(dir, "nostromo_add_cmd.md"))
	if err != nil {
		t.Fatal(err)
	}
	page := string(b)
	if !strings.HasPrefix(page, "---\ntitle: add cmd\n---\n\n# nostromo add cmd\n") {
		t.Errorf("expected front matter title and H1, got:\n%s", page)
	}
	if !strings.Contains(page, "\n## Options\n") || strings.Contains(page, "\n### ") {
		t.Errorf("expected cobra sections promoted to H2, got:\n%s", page)
	}
	if !strings.Contains(page, "[nostromo add](nostromo_add.md)") {
		t.Errorf("expected relative link to parent page")
	}
	if strings.Contains(page, "Auto generated by spf13/cobra") {
		t.Errorf("auto generated tag should be disabled")
	}

	b, err = os.ReadFile(filepath.Join(dir, "SUMMARY.md"))
	if err != nil {
		t.Fatal(err)
	}
	want := "* [nostromo](nostromo.md)\n" +
		"* [add](nostromo_add.md)\n" +
		"    * [add cmd](nostromo_add_cmd.md)\n" +
		"    * [add sub](nostromo_add_sub.md)\n" +
		"* [show](nostromo_show.md)\n"
	if string(b) != want {
		t.Errorf("unexpected SUMMARY.md:\n%s\nwant:\n%s", b, want)
	}
}

func TestGenerateDocsRemovesStalePages(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "nostromo_gone.md")
	keep := filepath.Join(dir, "index.md")
	for _, f := range []string{stale, keep} {
		if err := os.WriteFile(f, []byte("x"), 0644); err != nil {
			t.Fatal(err)
		}
	}

	if code := GenerateDocs(newDocsTestRoot(), dir); code != 0 {
		t.Fatalf("expected exit code 0, got %d", code)
	}

	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Errorf("stale generated page should be removed")
	}
	if _, err := os.Stat(keep); err != nil {
		t.Errorf("hand written pages must be kept: %s", err)
	}
}

func TestGenerateDocsIsDeterministic(t *testing.T) {
	dir := t.TempDir()
	root := newDocsTestRoot()

	if code := GenerateDocs(root, dir); code != 0 {
		t.Fatalf("expected exit code 0, got %d", code)
	}
	first := readDocsDir(t, dir)

	if code := GenerateDocs(root, dir); code != 0 {
		t.Fatalf("expected exit code 0, got %d", code)
	}
	second := readDocsDir(t, dir)

	if len(first) != len(second) {
		t.Fatalf("file count changed between runs: %d vs %d", len(first), len(second))
	}
	for name, content := range first {
		if second[name] != content {
			t.Errorf("%s changed between runs", name)
		}
	}
}

func TestDocTitle(t *testing.T) {
	tests := map[string]string{
		"/tmp/ref/nostromo.md":         "nostromo",
		"/tmp/ref/nostromo_add_cmd.md": "add cmd",
		"nostromo_show.md":             "show",
	}
	for in, want := range tests {
		if got := docTitle("nostromo", in); got != want {
			t.Errorf("docTitle(%q) = %q, want %q", in, got, want)
		}
	}
}

func readDocsDir(t *testing.T, dir string) map[string]string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	files := map[string]string{}
	for _, e := range entries {
		b, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			t.Fatal(err)
		}
		files[e.Name()] = string(b)
	}
	return files
}
